apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  DB_PORT: "5432"
  DB_NAME: "lab"
  DB_USER: "postgres"
  JWT_EXPIRES_IN: "24h"
  AUTH_SERVICE_URL: "http://auth-service.production.svc.cluster.local:3001"
  USER_SERVICE_URL: "http://user-service.production.svc.cluster.local:3002"
  ORDER_SERVICE_URL: "http://order-service.production.svc.cluster.local:3003"
